### ISSUE TITLE
Port GTKMaxGUI to Gtk+3

### ISSUE THREAD

**Issue by woollybah** [maxmods/bah.mod#25]
Since Gtk+2 is old, and Gtk+3 is new, we need a shiny Gtk+ MaxGUI going forward...

**Comment by GWRon** [comment]
Maybe do it in an extra module... so people could choose (as long as the old module keeps working)

**Comment by GWRon** [comment]
Never mind.. just replied to the email without looking at the recent actions to the repo (new gtk3-branch)

**Comment by woollybah** [comment]
🐹 :-)

**Comment by olejr** [comment]
What's the status of the gkt3 branch?
Asking because it's getting close to impossible to get current gtk modules working on new distro's.
OpenSuse 42.1 for example has no gtkhtml-3.19 anymore, I've also been unable to compile the rest of gtk2 stuff. Not that I've looked very hard & long at that problem yet..

**Comment by woollybah** [comment]
Everything appears to be (mostly?) working except the Canvas. MaxIDE is running okay as a Gtk3 app.
Canvas... well, this will be an issue. Ideally I would use Gtk's GL area widget, but that is not directly compatible with how BlitzMax does it's OpenGL - BlitzMax creates its own context - even for MaxGUI, which it is given a window to attach it to. Gtk3 presents a context for use, which may not be attached to X11, as BlitzMax's assumes it will be.

It would mean the GL stuff would probably need re-working to be more "pluggable". Much like we have with the audio drivers, and like I did with the joystick stuff, I suppose. As it stands, the GL modules sit on top of brl.glgraphics. We'd need some kind of default version and make glgraphics a stub.
This in turn would make things nice for the SDL modules, which must currently implement their own "glgraphics" module, and therefore have custom SDLGLMax2D modules, instead of using GLMax2D with a different glgraphics..

But I digress... :-p

The Gtk3 stuff is now in its own "namespace", just to make deploying it not rely on all my other stuff - which is a wee bit hefty.
I'll have a look at committing it in the near future.
I've only built it with webkitgtk so far, which may end up being the best one to use anyway - unless someone comes up with some different choices.

**Comment by GWRon** [comment]
> It would mean the GL stuff would probably need re-working to be more "pluggable". Much like we have with the audio drivers, and like I did with the joystick stuff, I suppose. As it stands, the GL modules sit on top of brl.glgraphics. We'd need some kind of default version and make glgraphics a stub.
This in turn would make things nice for the SDL modules, which must currently implement their own "glgraphics" module, and therefore have custom SDLGLMax2D modules, instead of using GLMax2D with a different glgraphics..

I think this would be a good thing (when things finally come together). Do not forget to throw a message to the developer if he still only imports "glgraphics" then compared to the _then_ "newly added module" (read: throw if no "non-stub" got registered as driver).


Regarding webkit: it is what most people use, so yes, it is a good choice, except there is some kind of "lightweight" lib for simpler purposes (html + css, no fancy other stuff as some apps might just want to display some html-docs)

**Comment by woollybah** [comment]
See https://github.com/maxmods/gtk.mod

Since I've been developing exclusively on 64-bit (therefore with NG), for the moment I can't currently guarantee your mileage for 32-bit on either NG or legacy BlitzMax.
I shall test those when I find some time.

But as you know, 64-bit is the future (current?) on Linux... ;-)
