### ISSUE TITLE
[ng] Problem building bah.libsmbclient

### ISSUE THREAD

**Issue by woollybah** [maxmods/bah.mod#6]
bah.libsmbclient doesn't currently build with bmx-ng.

**Comment by GWRon** [comment]
```
$ ./bmk makemods -a bah.libsmbclient
[  1%] Compiling:glue.cpp
/home/ronny/Arbeit/Programmieren/BlitzMaxNG/mod/bah.mod/libsmbclient.mod/glue.cpp:23:26: fatal error: libsmbclient.h: No such file or directory
 #include "libsmbclient.h"
                          ^
compilation terminated.
```
I have "libsmbclient-dev" and "libsmbclient" installed but it still does not have this file. Users trying to compile "Kodi" (XMBC) had to replace it with "samba-4.0/libsmbclient.h" - but this sounds as if you need "samba-4.0" then.

---
Regardless, it might now compile for you and the issue is obsolete.
