### ISSUE TITLE
[dbsqlite.mod] Null values in TList

### ISSUE THREAD

**Issue by HenriVi** [maxmods/bah.mod#74]
Hi,

upon closing the database connection using the db.close() method might in some extreme cases create an exception:

>"Can't insert null object in list"

Exception rises from this code block inside clearQueries method:

```
For Local q:TSQLiteResultSet = EachIn queries.Copy()    <---While copying the TList
	q.free()
Next
```

This exception is hard to reproduce, but I did manage to produce it once while compiling the multi_commit2.bmx example.

This happens at least in regular Bmax. 

-Henri

**Comment by GWRon** [comment]
@HenriVi 
Regarding your comment on the commit: 
eachIn list
vs
0 until list.count


The `e:element = eachIn list` should only return valid instances of type `element`. So there should not be any need to check for null. This is only needed for an array based access.

So I do not understand why the approach of "array based access" was used there (while not in some other areas of the code).

**Comment by HenriVi** [comment]
You do not need to check null in EachIn operator, but there was an additional copy method used in the same statement. Tlist copy method checks for null values, and throws an error if it finds one. Apparently, in some rare cases there can be a null value in the TList (maybe due to some external C-code ?) . In anycase, throwing a null error in production environment is not desired.

-Henri

**Comment by GWRon** [comment]
Ahh ok. So the "copy()" is flawed then. Copy should be able to recreate a list.
Maybe introduce a "Trim()" to a list which removes any null values... If one calls it then they know what can happen.

**Comment by GWRon** [comment]
@HenriVi 
Can you point me to where the `copy()` does that... Or was it an NG issue?

**Comment by HenriVi** [comment]
See below:

'''
Method Copy:TList()
	Local list:TList=New TList
	Local link:TLink=_head._succ
	While link<>_head
		list.AddLast link._value	' <-- link._value is asserted in AddLast-method
		link=link._succ
	Wend
	Return list
End Method
'''

This is not NG-related issue.

-Henri

**Comment by GWRon** [comment]
Ahh thanks for clarification (not that easy to traverse through code on your smartphone).

So if it was somehow possible to add or assign null (eg manipulating TLink content) then the assert would be @ kind of "bug" - at least in my opinion.

Using EachIn is one of the language features and removes some else needed lines ... aka keeps code more readable. This is why I wondered.

The done change now looks a bit like a patch instead of a cure.

**Comment by woollybah** [comment]
Thanks.

The problem with TList, is that things like Copy() or Reverse() can invoke the garbage collector - on account of all of the TLinks that need to be created.
So if you intended to use it via some object Delete(), via some cleanup code, etc, it's possible to get in a situation where an object removes itself from a list that you are half-way through copying.

The "cure", is not to rely on TList at all, and use an Array instead, which is far more predictable.

Of course, the perfect solution would be to not use Delete() at all, and require the user to manage all of the object lives themselves - freeing them as required. But then it wouldn't be so easy to use everything.

**Comment by GWRon** [comment]
So we could (theoretically) disable the GC before (if not done yet) and reenable it afterwards (if it was enabled)?

Somehow this sounds as if TList is no longer that cool if you add some objects whose interna you do not know (so whether they use Delete() or not).

Would be nice if the iterator knew about a free/change of the lists entries and took care of it for us accordingly.

**Comment by HurryStarfish** [comment]
> Somehow this sounds as if TList is no longer that cool if you add some objects whose interna you do not know (so whether they use Delete() or not).

If objects do something weird in their `Delete` methods, then that might cause problems, yeah. But that's true for everything that interacts with them; not just `TList`.
Having a `Delete` method doesn't *necessarily* break anything, but having a `Delete` method that causes side-effects such as manipulating a list is likely to. It's not just because `TList`s methods can cause garbage collections by allocating objects: in multithreaded programs, collections can be caused by other threads and `Delete` methods can run at any time and on any thread, simultaneously with any other code (including other `Delete` methods).

**Comment by GWRon** [comment]
Let me say it with different words:

In BlitzMax I can use a TList to store objects in it.
Now some of these objects do stuff which breaks/manipulates this TList.

Instead of correcting this "break" the patch just avoids that this odd behaviour leads to a crash/segfault.


This is what feels "dirty". Of course it might be a fault of TList too but still it is the matter of the utilizing code (here dbsqlite.mod) to behave nice so it does not manipulate external stuff (the tlist).

**Comment by HurryStarfish** [comment]
What I'm saying is basically: it looks like it's not the `TList` that's at fault here, but the objects stored in it - due to the behaviour effects their `Delete` methods cause.

That said, I've never used that module, so might not understand the problem here, but - from what I can see, these `TSQLiteResultSet` objects remove themselves from a collection during `Delete`. But this `Delete` method is only called once the object is unreachable/garbage, and since the collection holds a reference to it, that means the collection is also garbage, which means the `TDBSQLite` object containing the collection is garbage. Why do the `TSQLiteResultSet` objects need to be removed at that point?

**Comment by GWRon** [comment]
> What I'm saying is basically: it looks like it's not the TList that's at fault here, but the objects stored in it - due to the behaviour effects their Delete methods cause

That is what I wanted to say... In a way more concise manner :-)
